### ISSUE TITLE
Documentation improvement on the usage of "Fixed Masks"

### ISSUE THREAD

**Issue by DSbiomedAU** [embl-cba/elastixWrapper#16]
To use a Mask with multichannel data, it is necessary to also have a multichannel mask file. When attempting to use a single channel 8 bit  mask stack, the program will throw an exception message and no computation will be performed.
It makes complete sense in hindsight but it took some troubleshooting to figure out, the documentation could point that out in a more explicit fashion so other people working with this type of data may take advantage of the feature.

**Comment by tischi** [comment]
@DSbiomedAU 

Thank you very much for raising these issues. 

I was on holidays and will try to look at all of them during the coming days. 

Thank you for your patience!

**Comment by DSbiomedAU** [comment]
You're welcome, thank you for releasing this code!

**Comment by tischi** [comment]
@DSbiomedAU I tried improving the documentation in the README. Could you please have a look?

**Comment by DSbiomedAU** [comment]
@tischi much clearer thanks! I also had no idea that the wrapper was converting the masks to 0-1 binaries so I was always subtracting 254 to them just out of precaution. 
I don't know how useful it is, but the number of samples field also accepts multiple values when separated with a semicolon, my intuition is that it could be a good idea speed-wise to use a lower number of samples for a low res scale (e.g. 10x) and then increase the number of samples at higher resolution scales for finer registration passes. It is pretty obvious in hindsight but it never occurred to me that it was possible until I read your Groovy script example.

**Comment by tischi** [comment]
> I don't know how useful it is, but the number of samples field also accepts multiple values when separated with a semicolon, my intuition is that it could be a good idea speed-wise to use a lower number of samples for a low res scale (e.g. 10x) and then increase the number of samples at higher resolution scales for finer registration passes. 

Makes total sense!

I added this:

Note that a semicolon separated list can be provided to use a different number of samples for registration at different resolutions (the number of list items must match the number of list items in the below "Gaussian smoothing sigma" parameter). It usually makes sense to use relatively less samples for lower resolutions.

Good?

**Comment by DSbiomedAU** [comment]
Awesome thanks! 
I'm also using your BigWarp Affine to Transformix to initialize difficult registrations, this entire plugin makes my job so much easier. Hope to cite you soon!
