### ISSUE TITLE
Run elastix directly with compatible file types e.g. mhd

### ISSUE THREAD

**Issue by K-Meech** [embl-cba/elastixWrapper#8]
It would be great if the elastixWrapper could also handle images that don't need to be 'staged' - e.g. mhd files / nrrd files...

This would require separating the code involved in calling elastix on the command line from the code involved in staging files to .mhd format.

@tischi I'm happy to put a draft together, and do a PR - if you'd be happy with this change?

**Comment by tischi** [comment]
> It would be great if the elastixWrapper could also handle images that don't need to be 'staged' - e.g. mhd files / nrrd files...

You mean to avoid the temporary data duplication?

> This would require separating the code involved in calling elastix on the command line from the code involved in staging files to .mhd format.

Code separation is always a good thing :-) Sure, go ahead!

**Comment by K-Meech** [comment]
Yes! I have a bunch of mhd files (which can be quite large) that I'd like to avoid making further copies of.
Also, I'm calling it from another fiji plugin, so it'd be useful to be able to call the command line parts more directly.

**Comment by tischi** [comment]
Cool! Go for it!

**Comment by K-Meech** [comment]
@tischi  I noticed that in the plugin you only support 2 parameter styles: 'Default' and 'CLEM' https://github.com/embl-cba/elastixWrapper/blob/master/src/main/java/de/embl/cba/elastixwrapper/commands/ElastixCommand.java#L88, while you also have 'Hennings' implemented - https://github.com/embl-cba/elastixWrapper/blob/master/src/main/java/de/embl/cba/elastixwrapper/elastix/ElastixParameters.java#L163

Do you still need the 'Hennings' parameters? I'm rearranging some stuff, so I can take it out if it's no longer needed

**Comment by tischi** [comment]
Henning is no longer needed.
